version: "3.9"

services:
  api:
    container_name: fastapi_backend
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
        - "8001:8001"
    networks:
        - backend
    depends_on:
      - db
    command: "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    stdin_open: true
    tty: true

  db:
    container_name: db
    hostname: db
    image: postgres:15.4
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
      driver: local

networks:
  backend:
    name: backend
