version: "3.9"

services:
  api:
    container_name: fastapi_backend
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
        - "8001:8001"
    networks:
        - backend
    command: "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    stdin_open: true
    tty: true

networks:
  backend:
