version: "3.9"

services:
  api:
    container_name: fastapi_backend
    hostname: fastapi_backend
    env_file:
      - ./configs/local/api.env
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
        - "8001:8001"
    networks:
        - backend
    depends_on:
      - db
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    stdin_open: true
    tty: true

  db:
    container_name: db
    hostname: db
    image: postgres:15.4
    env_file:
      - ./configs/local/postgres.env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data_FAS:/var/lib/postgresql/data/

volumes:
    postgres_data_FAS:
      driver: local

networks:
  backend:
    name: backend
